#!/usr/bin/env bash

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build docs for available presentations and move them to a shared location"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        nix-shell --run \
            'sbt "akka-streams-advanced/mdoc;akka-streams-basics/mdoc"'
        cp -r akka-streams-advanced/docs presentations/akka-streams-advanced
        cp -r akka-streams-basics/docs presentations/akka-streams-basics
    fi
fi
